
name: MCSPEED
on:
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2

     - name: Download
       run: |
          sudo -i
          wget https://github.com/bangbang93/minecraft-proxy/releases/download/v1.4.5/minecraft-proxy.tar.gz
          tar -zxvf minecraft-proxy.tar.gz
          chmod +x ./bin/mcproxy
          rm config/config.yml
          wget -P config https://github.com/lem0nb/mcspeedip/raw/main/config.yml
          
     - name: Start
       run: |
          nohup ./bin/mcproxy &
          
          
     - name: Tunnel
       run: |
          wget https://github.com/open-dingtalk/pierced/raw/master/linux/ding
          wget https://github.com/lem0nb/mcspeedip/raw/main/ding.cfg
          chmod +x ding
          nohup ./ding -proto=tcp -config=./ding.cfg start ssh &
          
     - name: SSH connection to Actions
       uses: lem0nb/debugger-action@master
          
     - name: Sleep
       run: sleep 6h
